/**
 * This file contains pixel art for letters
 *
 * @author Patrick Stock
 */

const letterPixelArt = {
    A: ["    xx    ",
        "   xxxx   ",
        "  xxxxxx  ",
        "xxxx  xxxx",
        "xxx    xxx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xxxxxxxxxx",
        "xxxxxxxxxx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",],
    B: ["xxxxxxxx  ",
        "xxxxxxxxx ",
        "xx     xxx",
        "xx      xx",
        "xx      xx",
        "xx     xxx",
        "xxxxxxxxxx",
        "xxxxxxxxxx",
        "xx     xxx",
        "xx      xx",
        "xx      xx",
        "xx     xxx",
        "xxxxxxxxx ",
        "xxxxxxxx  ",],
    C: ["  xxxxxx  ",
        " xxxxxxxx ",
        "xxx    xxx",
        "xx      xx",
        "xx        ",
        "xx        ",
        "xx        ",
        "xx        ",
        "xx        ",
        "xx        ",
        "xx      xx",
        "xxx    xxx",
        " xxxxxxxx ",
        "  xxxxxx  ",],
    D: ["xxxxxxxx  ",
        "xxxxxxxxx ",
        "xx     xxx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx     xxx",
        "xxxxxxxxx ",
        "xxxxxxxx  ",],
    E: ["xxxxxxxxxx",
        "xxxxxxxxxx",
        "xx        ",
        "xx        ",
        "xx        ",
        "xx        ",
        "xxxxxxxx  ",
        "xxxxxxxx  ",
        "xx        ",
        "xx        ",
        "xx        ",
        "xx        ",
        "xxxxxxxxxx",
        "xxxxxxxxxx",],
    F: ["xxxxxxxxxx",
        "xxxxxxxxxx",
        "xx        ",
        "xx        ",
        "xx        ",
        "xx        ",
        "xxxxxxxx  ",
        "xxxxxxxx  ",
        "xx        ",
        "xx        ",
        "xx        ",
        "xx        ",
        "xx        ",
        "xx        ",],
    G: ["  xxxxxx  ",
        " xxxxxxxx ",
        "xxx    xxx",
        "xx      xx",
        "xx        ",
        "xx        ",
        "xx   xxxxx",
        "xx   xxxxx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xxx    xxx",
        " xxxxxxxx ",
        "  xxxxxx  ",],
    H: ["xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xxxxxxxxxx",
        "xxxxxxxxxx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",],
    I: [" xxxxxxxx ",
        " xxxxxxxx ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        " xxxxxxxx ",
        " xxxxxxxx ",],
    J: ["    xxxxxx",
        "    xxxxxx",
        "      xx  ",
        "      xx  ",
        "      xx  ",
        "      xx  ",
        "      xx  ",
        "      xx  ",
        "      xx  ",
        "      xx  ",
        "xx    xx  ",
        "xxx  xxx  ",
        " xxxxxx   ",
        "  xxxx    ",],
    K: ["xx      xx",
        "xx     xxx",
        "xx    xxx ",
        "xx   xxx  ",
        "xx  xxx   ",
        "xx xxx    ",
        "xxxxx     ",
        "xxxxx     ",
        "xx xxx    ",
        "xx  xxx   ",
        "xx   xxx  ",
        "xx    xxx ",
        "xx     xxx",
        "xx      xx",],
    L: ["xx        ",
        "xx        ",
        "xx        ",
        "xx        ",
        "xx        ",
        "xx        ",
        "xx        ",
        "xx        ",
        "xx        ",
        "xx        ",
        "xx        ",
        "xx        ",
        "xxxxxxxxxx",
        "xxxxxxxxxx",],
    M: ["xx      xx",
        "xx      xx",
        "xxx    xxx",
        "xxxx  xxxx",
        "xxxxxxxxxx",
        "xx xxxx xx",
        "xx  xx  xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",],
    N: ["xx      xx",
        "xx      xx",
        "xx      xx",
        "xxx     xx",
        "xxxx    xx",
        "xxxxx   xx",
        "xx xxx  xx",
        "xx  xxx xx",
        "xx   xxxxx",
        "xx    xxxx",
        "xx     xxx",
        "xx      xx",
        "xx      xx",
        "xx      xx",],
    O: ["  xxxxxx  ",
        " xxxxxxxx ",
        "xxx    xxx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xxx    xxx",
        " xxxxxxxx ",
        "  xxxxxx  ",],
    P: ["xxxxxxxx  ",
        "xxxxxxxxx ",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xxxxxxxxx ",
        "xxxxxxxx  ",
        "xx        ",
        "xx        ",
        "xx        ",
        "xx        ",
        "xx        ",
        "xx        ",],
    Q: ["  xxxxxx  ",
        " xxxxxxxx ",
        "xxx    xxx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx  xx  xx",
        "xx  xxx xx",
        "xx   xxxx ",
        "xxx   xxx ",
        " xxxxxxxxx",
        "  xxxx  xx",],
    R: ["xxxxxxxx  ",
        "xxxxxxxxx ",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xxxxxxxxx ",
        "xxxxxxxx  ",
        "xx xxx    ",
        "xx  xxx   ",
        "xx   xxx  ",
        "xx    xxx ",
        "xx     xxx",
        "xx      xx",],
    S: ["  xxxxxx  ",
        " xxxxxxxx ",
        "xxx    xxx",
        "xx      xx",
        "xx        ",
        "xxx       ",
        " xxxxxxx  ",
        "  xxxxxxx ",
        "       xxx",
        "        xx",
        "xx      xx",
        "xxx    xxx",
        " xxxxxxxx ",
        "  xxxxxx  ",],
    T: ["xxxxxxxxxx",
        "xxxxxxxxxx",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",],
    U: ["xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xxx    xxx",
        " xxxxxxxx ",
        "  xxxxxx  ",],
    V: ["xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xxx    xxx",
        " xxx  xxx ",
        "  xxxxxx  ",
        "   xxxx   ",
        "    xx    ",],
    W: ["xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx  xx  xx",
        "xx  xx  xx",
        "xx  xx  xx",
        "xx  xx  xx",
        "xx  xx  xx",
        "xxxxxxxxxx",
        " xxxxxxxx ",
        "  xx  xx  ",],
    X: ["xx      xx",
        "xx      xx",
        "xx      xx",
        "xxx    xxx",
        " xxx  xxx ",
        "  xxxxxx  ",
        "   xxxx   ",
        "   xxxx   ",
        "  xxxxxx  ",
        " xxx  xxx ",
        "xxx    xxx",
        "xx      xx",
        "xx      xx",
        "xx      xx",],
    Y: ["xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xxx    xxx",
        " xxx  xxx ",
        "  xxxxxx  ",
        "   xxxx   ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",],
    Z: ["xxxxxxxxxx",
        "xxxxxxxxxx",
        "        xx",
        "       xxx",
        "      xxx ",
        "     xxx  ",
        "    xxx   ",
        "   xxx    ",
        "  xxx     ",
        " xxx      ",
        "xxx       ",
        "xx        ",
        "xxxxxxxxxx",
        "xxxxxxxxxx",],
    a: ["          ",
        "          ",
        "          ",
        "  xxxxxxx ",
        "  xxxxxxxx",
        "       xxx",
        "        xx",
        "  xxxxx xx",
        " xxxxxxxxx",
        "xxx    xxx",
        "xx      xx",
        "xxx    xxx",
        " xxxxxxxxx",
        "  xxxxx xx",],
    b: ["xx        ",
        "xx        ",
        "xx        ",
        "xx  xxx   ",
        "xx xxxxx  ",
        "xxxxx xxx ",
        "xxx    xxx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xxx    xxx",
        "xxxxx xxx ",
        "xx xxxxx  ",
        "xx  xxx   ",],
    c: ["          ",
        "          ",
        "          ",
        "          ",
        "  xxxxxx  ",
        " xxxxxxxx ",
        "xxx    xxx",
        "xx      xx",
        "xx        ",
        "xx        ",
        "xx      xx",
        "xxx    xxx",
        " xxxxxxxx ",
        "  xxxxxx  ",],
    d: ["        xx",
        "        xx",
        "        xx",
        "   xxx  xx",
        "  xxxxx xx",
        "xxxx xxxxx",
        "xxx    xxx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xxx    xxx",
        "xxxx xxxxx",
        "  xxxxx xx",
        "   xxx  xx",],
    e: ["          ",
        "          ",
        "          ",
        "          ",
        "  xxxxxx  ",
        " xxxxxxxx ",
        "xxx    xxx",
        "xx      xx",
        "xxxxxxxxxx",
        "xxxxxxxxx ",
        "xx        ",
        "xxx    xxx",
        " xxxxxxxx ",
        "  xxxxxx  ",],
    f: ["     xxxx ",
        "    xxxxx ",
        "    xx    ",
        "    xx    ",
        " xxxxxxxx ",
        " xxxxxxxx ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",],
    g: ["          ",
        "          ",
        "  xxxxxx  ",
        " xxxxxxxx ",
        "xxx    xxx",
        "xx      xx",
        "xxx    xxx",
        " xxxxxxxxx",
        "  xxxxx xx",
        "        xx",
        "        xx",
        "xx     xxx",
        "xxxxxxxxx ",
        " xxxxxxx  ",],
    h: ["xx        ",
        "xx        ",
        "xx        ",
        "xx  xxx   ",
        "xx xxxxx  ",
        "xxxxx xxx ",
        "xxxx   xxx",
        "xxx     xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",],
    i: ["          ",
        "    xx    ",
        "    xx    ",
        "          ",
        "          ",
        "  xxxx    ",
        "  xxxx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xxx   ",
        "     xxx  ",
        "      xx  ",],
    j: ["    xx    ",
        "    xx    ",
        "          ",
        "  xxxx    ",
        "  xxxx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "   xxx    ",
        "xxxxx     ",
        "xxxx      ",],
    k: ["xx        ",
        "xx        ",
        "xx        ",
        "xx      xx",
        "xx     xxx",
        "xx    xxx ",
        "xx   xxx  ",
        "xx  xxx   ",
        "xx xxx    ",
        "xxxxxxx   ",
        "xxxx xxx  ",
        "xxx   xxx ",
        "xx     xxx",
        "xx      xx",],
    l: ["    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xxx   ",
        "     xxx  ",
        "      xx  ",],
    m: ["          ",
        "          ",
        "          ",
        "          ",
        "xx xxxxx  ",
        "xxxxxxxxx ",
        "xxx xx xxx",
        "xx  xx  xx",
        "xx  xx  xx",
        "xx  xx  xx",
        "xx  xx  xx",
        "xx  xx  xx",
        "xx  xx  xx",
        "xx  xx  xx",],
    n: ["          ",
        "          ",
        "          ",
        "          ",
        "xx xxxxx  ",
        "xxxxxxxxx ",
        "xxx    xxx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",],
    o: ["          ",
        "          ",
        "          ",
        "          ",
        "  xxxxxx  ",
        " xxxxxxxx ",
        "xxx    xxx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xxx    xxx",
        " xxxxxxxx ",
        "  xxxxxx  ",],
    p: ["          ",
        "          ",
        "          ",
        "xx xxxxx  ",
        "xxxxxxxxx ",
        "xxxx   xxx",
        "xxx     xx",
        "xxx     xx",
        "xxxx   xxx",
        "xxxxxxxxx ",
        "xx xxxxx  ",
        "xx        ",
        "xx        ",
        "xx        ",],
    q: ["          ",
        "          ",
        "          ",
        "  xxxxx xx",
        " xxxxxxxxx",
        "xxx   xxxx",
        "xx     xxx",
        "xx     xxx",
        "xxx   xxxx",
        " xxxxxxxxx",
        "  xxxxx xx",
        "        xx",
        "        xx",
        "        xx",],
    r: ["          ",
        "          ",
        "          ",
        "          ",
        "xx  xxxx  ",
        "xx xxxxxx ",
        "xxxxx  xxx",
        "xxxx    xx",
        "xxx       ",
        "xx        ",
        "xx        ",
        "xx        ",
        "xx        ",
        "xx        ",],
    s: ["          ",
        "          ",
        "          ",
        "          ",
        "  xxxxxx  ",
        " xxxxxxxx ",
        "xxx    xxx",
        "xxx     xx",
        " xxxxx    ",
        "    xxxxx ",
        "xx     xxx",
        "xxx    xxx",
        " xxxxxxxx ",
        "  xxxxxx  ",],
    t: ["    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        " xxxxxxxx ",
        " xxxxxxxx ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xxx   ",
        "     xxx  ",
        "      xx  ",],
    u: ["          ",
        "          ",
        "          ",
        "          ",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xxx    xxx",
        " xxxxxxxx ",
        "  xxxxxx  ",],
    v: ["          ",
        "          ",
        "          ",
        "          ",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xxx    xxx",
        " xxx  xxx ",
        "  xxxxxx  ",
        "   xxxx   ",
        "    xx    ",],
    w: ["          ",
        "          ",
        "          ",
        "          ",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xx  xx  xx",
        "xx  xx  xx",
        "xx  xx  xx",
        "xxx xx xxx",
        " xxxxxxxx ",
        "  xx  xx  ",],
    x: ["          ",
        "          ",
        "          ",
        "          ",
        "xx      xx",
        "xxx    xxx",
        " xxx  xxx ",
        "  xxxxxx  ",
        "   xxxx   ",
        "   xxxx   ",
        "  xxxxxx  ",
        " xxx  xxx ",
        "xxx    xxx",
        "xx      xx",],
    y: ["          ",
        "          ",
        "          ",
        "xx      xx",
        "xx      xx",
        "xx     xxx",
        "xx     xxx",
        "xxx   xxxx",
        " xxxxxxxxx",
        "  xxxxx xx",
        "        xx",
        "       xxx",
        "  xxxxxxx ",
        "  xxxxxx  ",],
    z: ["          ",
        "          ",
        "          ",
        "          ",
        "xxxxxxxxxx",
        "xxxxxxxxxx",
        "      xxx ",
        "     xxx  ",
        "    xxx   ",
        "   xxx    ",
        "  xxx     ",
        " xxx      ",
        "xxxxxxxxxx",
        "xxxxxxxxxx",],
    1: ["    xx    ",
        "   xxx    ",
        "  xxxx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",
        "    xx    ",],
    2: ["    xx    ",
        "  xxxxxx  ",
        " xxxxxxxx ",
        " xxx  xxx ",
        "xxx    xxx",
        "       xxx",
        "      xxx ",
        "     xxx  ",
        "    xxx   ",
        "   xxx    ",
        "  xxx     ",
        " xxx      ",
        "xxxxxxxxxx",
        "xxxxxxxxxx",],
    3: ["   xxxx   ",
        "  xxxxxx  ",
        " xxx  xxx ",
        " xx    xxx",
        "       xxx",
        "      xxx ",
        "   xxxxx  ",
        "   xxxxx  ",
        "      xxx ",
        "       xxx",
        " xx    xxx",
        " xxx  xxx ",
        "  xxxxxx  ",
        "   xxxx   ",],
    4: ["      xx  ",
        "     xxx  ",
        "    xxxx  ",
        "   xxxxx  ",
        "  xxx xx  ",
        " xxx  xx  ",
        "xxx   xx  ",
        "xxxxxxxxxx",
        "xxxxxxxxxx",
        "      xx  ",
        "      xx  ",
        "      xx  ",
        "      xx  ",
        "      xx  ",],
    5: ["xxxxxxxxxx",
        "xxxxxxxxxx",
        "xx        ",
        "xx        ",
        "xx        ",
        "xxxxxxx   ",
        "xxxxxxxx  ",
        "      xxx ",
        "       xxx",
        "       xxx",
        "xx     xxx",
        "xxx   xxx ",
        " xxxxxxx  ",
        "  xxxxx   ",],
    6: ["  xxxxxx  ",
        " xxxxxxxx ",
        "xxx    xxx",
        "xx        ",
        "xx        ",
        "xxxxxxxx  ",
        "xxxxxxxxx ",
        "xxx    xxx",
        "xx      xx",
        "xx      xx",
        "xx      xx",
        "xxx    xxx",
        " xxxxxxxx ",
        "  xxxxxx  ",],
    7: ["xxxxxxxxxx",
        "xxxxxxxxxx",
        "       xxx",
        "       xxx",
        "      xxx ",
        "      xxx ",
        "     xxx  ",
        "     xxx  ",
        "    xxx   ",
        "    xxx   ",
        "   xxx    ",
        "   xxx    ",
        "  xxx     ",
        "  xxx     ",],
    8: ["  xxxxxx  ",
        " xxxxxxxx ",
        "xxx    xxx",
        "xx      xx",
        "xx      xx",
        "xxx    xxx",
        " xxxxxxxx ",
        " xxxxxxxx ",
        "xxx    xxx",
        "xx      xx",
        "xx      xx",
        "xxx    xxx",
        " xxxxxxxx ",
        "  xxxxxx  ",],
    9: ["  xxxxxx  ",
        " xxxxxxxx ",
        "xxx    xxx",
        "xx      xx",
        "xx      xx",
        "xxx    xxx",
        " xxxxxxxxx",
        "  xxxxxxxx",
        "      xxx ",
        "      xxx ",
        "     xxx  ",
        "     xxx  ",
        "    xxx   ",
        "    xxx   ",],
    0: ["  xxxxxx  ",
        " xxxxxxxx ",
        "xxx    xxx",
        "xx     xxx",
        "xx    xxxx",
        "xx   xxxxx",
        "xx  xxx xx",
        "xx xxx  xx",
        "xxxxx   xx",
        "xxxx    xx",
        "xxx     xx",
        "xxx    xxx",
        " xxxxxxxx ",
        "  xxxxxx  ",],
    colon: ["          ",
        "          ",
        "          ",
        "          ",
        "xx        ",
        "xx        ",
        "          ",
        "          ",
        "          ",
        "          ",
        "          ",
        "          ",
        "xx        ",
        "xx        ",],
    period: ["          ",
        "          ",
        "          ",
        "          ",
        "          ",
        "          ",
        "          ",
        "          ",
        "          ",
        "          ",
        "          ",
        "          ",
        "xx        ",
        "xx        ",],
    space: ["          ",
        "          ",
        "          ",
        "          ",
        "          ",
        "          ",
        "          ",
        "          ",
        "          ",
        "          ",
        "          ",
        "          ",
        "          ",
        "          ",],
};

const letterMap = new Map([
    ["A", letterPixelArt.A],
    ["B", letterPixelArt.B],
    ["C", letterPixelArt.C],
    ["D", letterPixelArt.D],
    ["E", letterPixelArt.E],
    ["F", letterPixelArt.F],
    ["G", letterPixelArt.G],
    ["H", letterPixelArt.H],
    ["I", letterPixelArt.I],
    ["J", letterPixelArt.J],
    ["K", letterPixelArt.K],
    ["L", letterPixelArt.L],
    ["M", letterPixelArt.M],
    ["N", letterPixelArt.N],
    ["O", letterPixelArt.O],
    ["P", letterPixelArt.P],
    ["Q", letterPixelArt.Q],
    ["R", letterPixelArt.R],
    ["S", letterPixelArt.S],
    ["T", letterPixelArt.T],
    ["U", letterPixelArt.U],
    ["V", letterPixelArt.V],
    ["W", letterPixelArt.W],
    ["X", letterPixelArt.X],
    ["Y", letterPixelArt.Y],
    ["Z", letterPixelArt.Z],
    ["a", letterPixelArt.a],
    ["b", letterPixelArt.b],
    ["c", letterPixelArt.c],
    ["d", letterPixelArt.d],
    ["e", letterPixelArt.e],
    ["f", letterPixelArt.f],
    ["g", letterPixelArt.g],
    ["h", letterPixelArt.h],
    ["i", letterPixelArt.i],
    ["j", letterPixelArt.j],
    ["k", letterPixelArt.k],
    ["l", letterPixelArt.l],
    ["m", letterPixelArt.m],
    ["n", letterPixelArt.n],
    ["o", letterPixelArt.o],
    ["p", letterPixelArt.p],
    ["q", letterPixelArt.q],
    ["r", letterPixelArt.r],
    ["s", letterPixelArt.s],
    ["t", letterPixelArt.t],
    ["u", letterPixelArt.u],
    ["v", letterPixelArt.v],
    ["w", letterPixelArt.w],
    ["x", letterPixelArt.x],
    ["y", letterPixelArt.y],
    ["z", letterPixelArt.z],
    [":", letterPixelArt.colon],
    [".", letterPixelArt.period],
    [" ", letterPixelArt.space],
    ["1", letterPixelArt[1]],
    ["2", letterPixelArt[2]],
    ["3", letterPixelArt[3]],
    ["4", letterPixelArt[4]],
    ["5", letterPixelArt[5]],
    ["6", letterPixelArt[6]],
    ["7", letterPixelArt[7]],
    ["8", letterPixelArt[8]],
    ["9", letterPixelArt[9]],
    ["0", letterPixelArt[0]],
]);

function stringToPixelArt(inputString) {
    let output = [];
    let currLine = [];

    for (let i = 0; i < inputString.length; i++) {
        if (inputString[i] === "\n") {
            output.push(currLine);
            currLine = [];
        } else {
            currLine.push(letterMap.get(inputString[i]));
        }
    }
    output.push(currLine);

    return output;
}